.PHONY: clean All

All:
	@echo "----------Building project:[ TP2 - Debug ]----------"
	@cd "/users/info/etu-s4/bassetlu/Lucas/TP2" && "$(MAKE)" -f  "TP2.mk"
clean:
	@echo "----------Cleaning project:[ TP2 - Debug ]----------"
	@cd "/users/info/etu-s4/bassetlu/Lucas/TP2" && "$(MAKE)" -f  "TP2.mk" clean
