.PHONY: clean All

All:
	@echo "----------Building project:[ projet - Debug ]----------"
	@cd "projet" && "$(MAKE)" -f  "projet.mk"
clean:
	@echo "----------Cleaning project:[ projet - Debug ]----------"
	@cd "projet" && "$(MAKE)" -f  "projet.mk" clean
